# Site settings
title: Justin Lee
name: Justin Lee
korean_name: 이다호
email: justindaholee@gmail.com
occupation: PhD Student
employer: University of Washington
# office:
department: Molecular Engineering
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Justin Lee, UW MolES PhD student
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justindaholee.github.io" # the base hostname & protocol for your site
twitter_username: justindaholee
github_username:  justindaholee

# Build settings
markdown: kramdown
